# Generated by Django 3.2.3 on 2022-08-06 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # ('product', '0003_auto_20220806_1051'),
        ('order', '0007_alter_orderitem_product'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='ProductVariantDetail',
        # ),
        # migrations.AddField(
        #     model_name='product',
        #     name='color_variant',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.colorvariant'),
        # ),
        # migrations.AddField(
        #     model_name='product',
        #     name='size',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.size'),
        # ),
    ]
