# Generated by Django 3.2.3 on 2022-08-06 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('product', '0002_rename_product_parentproduct'),
        ('product', '0004_auto_20220806_1051'),
    ]

    operations = [
    ]
