# Generated by Django 3.2.3 on 2022-08-06 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('product', '0005_merge_20220806_1143'),
    ]

    operations = [
    ]
