# Generated by Django 3.2.3 on 2021-06-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210602_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
