# Generated by Django 3.2.3 on 2021-06-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_seller_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
