# Generated by Django 3.2.3 on 2021-06-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_seller_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/sellers/'),
        ),
        migrations.AddField(
            model_name='seller',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/thumbnail/sellers/'),
        ),
    ]
