# Generated by Django 3.2.3 on 2021-06-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20210602_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
