# Generated by Django 3.2.3 on 2022-06-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20220619_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
