# Generated by Django 3.2.3 on 2022-06-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20220620_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
