# Generated by Django 3.2.3 on 2022-06-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20220620_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='main_variant',
            field=models.BooleanField(default=False),
        ),
    ]
