# Generated by Django 3.2.3 on 2022-06-20 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_productdetails_main_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
