# Generated by Django 3.2.3 on 2022-06-20 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20220620_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productdetails',
            name='image_url',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField(max_length=500)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='productdetails',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productimage'),
        ),
    ]
