# Generated by Django 3.2.3 on 2022-06-20 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20220620_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('main_variant', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='ProductImage',
            new_name='ProductVariant',
        ),
        migrations.DeleteModel(
            name='ProductDetails',
        ),
        migrations.AddField(
            model_name='productvariantdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productvariant'),
        ),
        migrations.AddField(
            model_name='productvariantdetail',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.size'),
        ),
    ]
