# Generated by Django 3.2.3 on 2022-06-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_remove_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariantdetail',
            name='main_variant',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='main_variant',
            field=models.BooleanField(default=False),
        ),
    ]
