# Generated by Django 3.2.3 on 2022-06-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20220620_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
