# Generated by Django 3.2.3 on 2022-06-20 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_productvariant_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='product',
            new_name='parent_product',
        ),
    ]
