# Generated by Django 3.2.3 on 2022-06-20 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_rename_product_productvariant_parent_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariantdetail',
            old_name='product',
            new_name='product_variant',
        ),
    ]
