# Generated by Django 3.2.3 on 2022-07-16 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_testp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestP',
        ),
    ]
