# Generated by Django 3.2.3 on 2022-08-15 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_orderitem_reviewed'),
        ('reviews', '0005_auto_20220815_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.orderitem'),
        ),
    ]
