# Generated by Django 3.2.3 on 2021-05-20 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210520_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default='Yet to dispatch', null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.orderstatus'),
        ),
    ]
