# Generated by Django 3.2.3 on 2022-08-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_done',
            field=models.BooleanField(default=False),
        ),
    ]
