# Generated by Django 3.2.3 on 2022-08-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dispatched_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
