# Generated by Django 3.2.3 on 2022-07-16 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_orderitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
