# Generated by Django 3.2.3 on 2022-07-18 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20220718_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paid_amount',
            new_name='packaging_fees',
        ),
    ]
