# Generated by Django 3.2.3 on 2022-07-18 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_rename_paid_amount_order_packaging_fees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_amount',
            new_name='sub_total',
        ),
    ]
