# Generated by Django 3.2.3 on 2022-08-20 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20220820_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='data',
            new_name='payment_data',
        ),
    ]
