# Generated by Django 3.2.3 on 2022-08-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20220820_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
